import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {randomUUID} from 'node:crypto';

test('4A: PostgreSQL local, valor interno, snapshots, permisos y rollback',async()=>{
 const db=new PGlite();
 try{
  await db.exec((await readFile('tests/phase3a.test.mjs','utf8')).match(/await db.exec\(`([\s\S]*?)`\);/)[1]);
  for(const file of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile('supabase/migrations/'+file,'utf8'));
  await mkdir('test-results',{recursive:true});
  await writeFile('test-results/phase4a-local-schema.json',JSON.stringify((await db.query(await readFile('tests/sql/phase4a-schema.sql','utf8'))).rows[0].fingerprint));
  const admin=randomUUID(),member=randomUUID(),inactive=randomUUID(),mat=randomUUID(),second=randomUUID();
  await db.query('insert into auth.users(id,email) values ($1,$4),($2,$5),($3,$6)',[admin,member,inactive,'inventory-admin@example.test','inventory-member@example.test','inventory-inactive@example.test']);
  await db.query("update public.profiles set role='admin' where id=$1",[admin]);
  await db.query("update public.profiles set status='inactive' where id=$1",[inactive]);
  await db.query("insert into public.materials(id,code,name,category,unit,min_stock) values ($1,'INV-1','Material prueba','Hilo','gramos',10),($2,'INV-2','Otro material','Hilo','gramos',0)",[mat,second]);
  await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[admin]);
  const payload=(m=mat,q='3',amount='10',extra={})=>({kind:'purchase',source_reference:'Prueba local 4A',lines:[{material_id:m,unit:'gramos',quantity:q,amount,currency:'CRC',...extra}]});
  const register=(p,rev,id=randomUUID())=>db.query('select public.register_inventory_receipt($1,$2,$3)',[id,p,rev]);
  const fail=async(p,rev,code='22023')=>assert.rejects(register(p,rev),e=>e.code===code);
  const first=randomUUID();await register(payload(),{[mat]:'0'},first);
  let v=(await db.query('select * from public.inventory_valuations_read where material_id=$1',[mat])).rows[0];
  assert.equal(v.value_crc,'10');assert.equal(v.average_unit_cost_crc,'3.33333333');
  assert.equal((await db.query('select rounding_delta_crc::text n from public.inventory_movement_costs')).rows[0].n,'0.00000001');
  await register(payload(mat,'3','11'),{[mat]:'1'});
  v=(await db.query('select * from public.inventory_valuations_read where material_id=$1',[mat])).rows[0];assert.equal(v.value_crc,'21');assert.equal(v.average_unit_cost_crc,'3.50000000');
  assert.equal((await db.query("select round(0.000000005::numeric,8)::text n")).rows[0].n,'0.00000001');
  await assert.rejects(register(payload(),{[mat]:'2'},first),e=>e.code==='PT409');
  await fail(payload(),{[mat]:'0'},'PT409');
  for(const q of ['0','-1','1.00001','NaN','Infinity'])await fail(payload(mat,q),{[mat]:'2'});
  for(const amount of ['0','-1','1.001','NaN'])await fail(payload(mat,'1',amount),{[mat]:'2'});
  await fail(payload(mat,'100000000','0.01'),{[mat]:'2'});
  await fail({...payload(),effective_at:'1901-01-01T00:00:00-06:00'},{[mat]:'2'});
  await fail({...payload(),effective_at:'2999-01-01T00:00:00-06:00'},{[mat]:'2'});
  await fail({...payload(),lines:[...payload().lines,...payload(second,'0').lines]},{[mat]:'2',[second]:'0'});
  assert.equal((await db.query('select revision::text n from public.inventory_balances where material_id=$1',[mat])).rows[0].n,'2');
  assert.equal((await db.query('select count(*)::int n from public.inventory_balances where material_id=$1',[second])).rows[0].n,0);
  await register({...payload(second),kind:'opening_balance',reason:'Inventario inicial valorado'},{[second]:'0'});
  await fail({...payload(second),kind:'opening_balance',reason:'Otro saldo'},{[second]:'1'},'PT409');
  await assert.rejects(db.query("update public.materials set unit='metros' where id=$1",[mat]),e=>e.code==='22023');
  await assert.rejects(db.query('update public.inventory_balances set quantity_on_hand=100 where material_id=$1',[mat]),e=>e.code==='42501');
  await db.query("update public.materials set is_active=false where id=$1",[second]);await fail(payload(second),{[second]:'1'});
  const usd=randomUUID();await db.exec('reset role');await db.query("insert into public.materials(id,code,name,category,unit) values($1,'INV-USD','USD','Hilo','gramos')",[usd]);await db.exec('set role authenticated');
  await register({...payload(usd,'2','1.25',{currency:'USD',historical_rate:'501.2345',rate_reason:'Referencia histórica de prueba',rate_source:'Documento histórico local'}),effective_at:'1901-01-01T12:00:00-06:00'},{[usd]:'0'});
  const item=(await db.query('select * from public.inventory_receipt_items_read where material_id=$1',[usd])).rows[0];assert.equal(item.amount_crc,'626.54');assert.equal(item.rate_origin,'admin_historical');
  await fail({...payload(usd,'2','1.25',{currency:'USD'}),effective_at:'1901-01-02T12:00:00-06:00'},{[usd]:'1'});
  const fx=randomUUID();await db.exec('reset role');
  await db.query("insert into public.materials(id,code,name,category,unit) values($1,'INV-FX','FX local','Hilo','gramos')",[fx]);await db.exec('set role authenticated');
  await fail(payload(fx,'1','2',{currency:'USD'}),{[fx]:'0'});
  await db.exec('reset role');await db.exec("insert into public.exchange_rates(source,rate_date,sell_rate) values('BCCR via tipodecambio.paginasweb.cr','1902-01-01',500)");await db.exec('set role authenticated');
  await register(payload(fx,'1','2',{currency:'USD'}),{[fx]:'0'});
  const fallback=(await db.query('select * from public.inventory_receipt_items_read where material_id=$1',[fx])).rows[0];
  assert.equal(fallback.rate_is_fallback,true);assert.equal(fallback.exchange_rate_date.toISOString().slice(0,10),'1902-01-01');assert.equal(fallback.amount_crc,'1000.00');
  await db.exec('reset role');await db.exec("insert into public.exchange_rates(source,rate_date,sell_rate) values('BCCR via tipodecambio.paginasweb.cr',(clock_timestamp() at time zone 'America/Costa_Rica')::date,501)");await db.exec('set role authenticated');
  await register(payload(fx,'1','2',{currency:'USD'}),{[fx]:'1'});
  const current=(await db.query('select * from public.inventory_receipt_items_read where material_id=$1 order by position',[fx])).rows;
  assert.ok(current.some(i=>!i.rate_is_fallback&&i.amount_crc==='1002.00'));
  assert.deepEqual(current.find(i=>i.id===fallback.id),fallback);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[member]);
  assert.equal((await db.query('select count(*)::int n from public.inventory_valuations')).rows[0].n,0);
  assert.equal((await db.query('select count(*)::int n from public.inventory_receipt_items')).rows[0].n,0);
  assert.ok((await db.query('select count(*)::int n from public.inventory_movements')).rows[0].n>0);
  await fail(payload(),{[mat]:'2'},'42501');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[inactive]);assert.equal((await db.query('select count(*)::int n from public.inventory_stock_read')).rows[0].n,0);
  await fail(payload(),{[mat]:'2'},'42501');
  await db.exec('reset role;set role anon');await assert.rejects(db.query('select * from public.inventory_stock_read'),e=>e.code==='42501');
 }finally{await db.close();}
});
