import {randomUUID} from 'node:crypto';
import Link from 'next/link';
import {requireProfile} from '@/lib/auth';
import {createClient} from '@/lib/supabase/server';
import {InventoryOperations} from '@/components/inventory-operations';
import {movementLabels,type StockOption,type OrderOption,type ItemOption,type MovementOption} from '@/features/inventory/operation-types';
type Attribution={id:string;movement_id:string;previous_order_id:string;previous_order_item_id:string|null;corrected_order_id:string;corrected_order_item_id:string|null;reason:string;created_at:string;created_by:string;revision:number};
export default async function InventoryOperationsPage({searchParams}:{searchParams:Promise<{material?:string;order?:string;page?:string}>}){
 const actor=await requireProfile(),client=await createClient(),query=await searchParams;
 async function all<T>(table:string,columns:string){const result:T[]=[];for(let offset=0;;offset+=500){const r=await client.from(table).select(columns).order('id').range(offset,offset+499);if(r.error)throw Error('No se pudo cargar el inventario. Reintenta la consulta.');result.push(...r.data as T[]);if(r.data.length<500)return result;}}
 const [materials,orders,items,movements]=await Promise.all([all<StockOption>('inventory_stock_read','id,code,name,unit,stock,revision,is_active'),all<OrderOption>('quotes_read','id,order_number,production_status,revision'),all<ItemOption>('quote_items_read','id,order_id,product_name_snapshot,is_active'),all<MovementOption>('inventory_operations_read','*')]);
 const costs:Record<string,{assigned_value_crc:string;unit_cost_applied_crc:string;rounding_delta_crc:string}>={};
 if(actor.role==='admin'){for(let offset=0;;offset+=500){const r=await client.from('inventory_operation_costs_read').select('movement_id,assigned_value_crc,unit_cost_applied_crc,rounding_delta_crc').order('movement_id').range(offset,offset+499);if(r.error)throw Error('No se pudo consultar la valoración.');for(const c of r.data)costs[c.movement_id]=c;if(r.data.length<500)break;}}
 const matching=movements.filter(m=>(!query.material||m.material_id===query.material)&&(!query.order||m.order_id===query.order)).sort((a,b)=>b.effective_at.localeCompare(a.effective_at)||b.id.localeCompare(a.id));
 const pages=Math.max(1,Math.ceil(matching.length/25)),page=Math.min(pages,Math.max(1,Number.parseInt(query.page??'1',10)||1)),visible=matching.slice((page-1)*25,page*25);
 const corrections:Attribution[]=[];
 const corrected=visible.filter(m=>Number(m.attribution_revision)>0).map(m=>m.id);
 if(corrected.length){const r=await client.from('inventory_movement_attribution_corrections').select('*').in('movement_id',corrected).order('revision');if(r.error)throw Error('No se pudo consultar el historial de atribución.');corrections.push(...r.data);}
 const orderName=(id:string)=>orders.find(o=>o.id===id)?.order_number??id;
 const pageUrl=(n:number)=>{const params=new URLSearchParams({page:String(n)});if(query.material)params.set('material',query.material);if(query.order)params.set('order',query.order);return `/inventario/operaciones?${params}`;};
 return <><Link href="/inventario" className="text-link">Volver al inventario</Link><h1>Consumos y devoluciones</h1><p>Registra el material utilizado y conserva su historial por pedido.</p><InventoryOperations initialRequestId={randomUUID()} admin={actor.role==='admin'} materials={materials} orders={orders} items={items} movements={movements} initialMaterial={query.material??''} initialOrder={query.order??''}/><h2>Historial operativo</h2>{!visible.length?<p className="message">Sin movimientos en esta selección.</p>:<div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Fecha</th><th>Material</th><th>Operación</th><th>Cantidad</th><th>Pedido / motivo</th>{actor.role==='admin'&&<th>Valoración privada CRC</th>}</tr></thead><tbody>{visible.map(m=><tr key={m.id}><td data-label="Fecha">{new Date(m.effective_at).toLocaleString('es-CR',{timeZone:'America/Costa_Rica'})}</td><td data-label="Material">{materials.find(x=>x.id===m.material_id)?.name}</td><td data-label="Operación">{movementLabels[m.movement_type]}<small className="muted"> · {m.id}</small></td><td data-label="Cantidad">{m.quantity}{m.returnable_quantity!==null&&<small> · retornable {m.returnable_quantity}</small>}</td><td data-label="Pedido / motivo">{m.order_id&&<Link href={`/pedidos/${m.order_id}`}>{orders.find(o=>o.id===m.order_id)?.order_number??'Pedido'}</Link>}<p>{m.reason}</p>{Number(m.attribution_revision)>0&&<details><summary>Atribución corregida · revisión {m.attribution_revision}</summary>{corrections.filter(c=>c.movement_id===m.id).map(c=><div key={c.id}><p>{orderName(c.previous_order_id)} → {orderName(c.corrected_order_id)}</p><p>Línea anterior: {c.previous_order_item_id?items.find(i=>i.id===c.previous_order_item_id)?.product_name_snapshot??c.previous_order_item_id:'Pedido completo'} · Nueva: {c.corrected_order_item_id?items.find(i=>i.id===c.corrected_order_item_id)?.product_name_snapshot??c.corrected_order_item_id:'Pedido completo'}</p><p>{c.reason}</p><small>{new Date(c.created_at).toLocaleString('es-CR',{timeZone:'America/Costa_Rica'})} · Actor {c.created_by} · Revisión {c.revision}</small></div>)}</details>}</td>{actor.role==='admin'&&<td data-label="Valoración CRC">{costs[m.id]&&<><p>Valor asignado: {costs[m.id].assigned_value_crc}</p><p>Promedio / costo snapshot: {costs[m.id].unit_cost_applied_crc}</p><small>Delta de precisión: {costs[m.id].rounding_delta_crc}</small></>}</td>}</tr>)}</tbody></table></div>}<nav className="form-actions" aria-label="Páginas del historial">{page>1&&<Link className="button secondary" href={pageUrl(page-1)}>Anterior</Link>}<span>Página {page} de {pages} · {matching.length} movimientos</span>{page<pages&&<Link className="button secondary" href={pageUrl(page+1)}>Siguiente</Link>}</nav></>;
}
