-- Solo lectura. Proyecta defaults de columnas nuevas para comprobar filas previas.
with candidate as (select o.*,null::integer number_year,null::bigint number_sequence,null::numeric deposit_percentage_applied,null::numeric deposit_required_amount,1::bigint commercial_revision,null::bigint zero_total_authorized_revision from public.orders o)
select jsonb_build_object('rows',(select count(*) from candidate),'violations',jsonb_build_object(
'orders_3b_status_check',(select count(*) from candidate where (production_status in ('quote','confirmed','in_production','ready','delivered','cancelled')) is not true),
'orders_3b_number_check',(select count(*) from candidate where (case when confirmed_at is null then order_number is null and number_year is null and number_sequence is null and deposit_percentage_applied is null and deposit_required_amount is null else order_number is not null and number_year is not null and number_sequence is not null and number_sequence>0 and number_year=extract(year from confirmed_at at time zone 'America/Costa_Rica') and order_number='PED-'||number_year::text||'-'||lpad(number_sequence::text,greatest(5,length(number_sequence::text)),'0') and deposit_percentage_applied is not null and deposit_percentage_applied between 0 and 100 and deposit_required_amount is not null end) is not true),
'orders_3b_confirmation_check',(select count(*) from candidate where (((production_status='quote' and confirmed_at is null) or production_status='cancelled' or (production_status in ('confirmed','in_production','ready','delivered') and confirmed_at is not null)) and (confirmed_at is null or (confirmed_at at time zone 'America/Costa_Rica')::date>=order_date)) is not true),
'orders_3b_delivery_check',(select count(*) from candidate where (case when production_status='delivered' then delivered_at is not null and confirmed_at is not null and delivered_at>=confirmed_at else delivered_at is null end) is not true),
'orders_3b_zero_actor_check',(select count(*) from candidate where (case when confirmed_at is not null and total=0 then zero_total_authorized_by is not null and zero_total_authorized_at is not null and zero_total_reason is not null and zero_total_authorized_revision is not null and zero_total_authorized_revision=commercial_revision else zero_total_authorized_by is null and zero_total_authorized_at is null and zero_total_reason is null and zero_total_authorized_revision is null end) is not true),
'orders_3b_zero_time_check',(select count(*) from candidate where (zero_total_authorized_at is null or (confirmed_at is not null and zero_total_authorized_at>=confirmed_at)) is not true),
'orders_3b_zero_reason_check',(select count(*) from candidate where (zero_total_reason is null or length(trim(zero_total_reason)) between 1 and 1000) is not true),
'orders_3b_cancellation_check',(select count(*) from candidate where (case when production_status='cancelled' then cancelled_at is not null and cancelled_by is not null and cancel_reason is not null and length(trim(cancel_reason)) between 1 and 1000 else cancelled_at is null and cancelled_by is null and cancel_reason is null end) is not true)
),'checks',(select jsonb_agg(jsonb_build_object('name',conname,'expression',pg_get_constraintdef(oid)) order by conname) from pg_constraint where conrelid='public.orders'::regclass and conname in ('orders_production_status_check','orders_order_number_check','orders_confirmed_at_check','orders_delivered_at_check','orders_zero_total_authorized_by_check','orders_zero_total_authorized_at_check','orders_zero_total_reason_check','orders_check2')),
'orders_hash',(select md5(coalesce(string_agg(to_jsonb(o)::text,'' order by id),'')) from public.orders o),
'audit_hash',(select md5(coalesce(string_agg(to_jsonb(a)::text,'' order by id),'')) from public.audit_log a)) as preflight;
