select jsonb_build_object(
'columns',(select md5(string_agg(table_name||'.'||column_name||':'||data_type||':'||udt_name||':'||is_nullable||':'||coalesce(column_default,''),E'\n' order by table_name,ordinal_position)) from information_schema.columns where table_schema='public' and table_name in ('orders','order_items','order_files','payments','order_counters','quotes_read','quote_items_read','quote_products_read','payments_read','order_payment_summary')),
'constraints',(select md5(string_agg(c.conname||':'||pg_get_constraintdef(c.oid),E'\n' order by c.conname)) from pg_constraint c where c.contype<>'n' and (c.conrelid in ('public.orders'::regclass,'public.order_items'::regclass,'public.order_files'::regclass,'public.payments'::regclass,'public.order_counters'::regclass) or c.contypid='public.quote_money'::regtype)),
'functions',(select md5(string_agg(pg_get_functiondef(p.oid),E'\n' order by n.nspname,p.proname)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.proname in ('save_quote','cancel_quote','register_order_file','quote_input_money','confirm_order','register_payment','void_payment','transition_order','amend_order','correct_order_dates','order_history','order_deposit_default','lock_order','order_reason','order_effective_at','order_event','guard_payment')),
'policies',(select md5(string_agg(policyname||':'||cmd||':'||coalesce(qual,'')||':'||coalesce(with_check,''),E'\n' order by policyname)) from pg_policies where tablename in ('orders','order_items','order_files','payments','order_counters') or policyname='order_references_read'),
'indexes',(select md5(string_agg(indexdef,E'\n' order by indexname)) from pg_indexes where schemaname='public' and tablename in ('orders','order_items','order_files','payments','order_counters')),
'views',(select md5(string_agg(viewname||':'||definition,E'\n' order by viewname)) from pg_views where schemaname='public' and viewname in ('quotes_read','quote_items_read','payments_read','order_payment_summary')),
'triggers',(select md5(string_agg(pg_get_triggerdef(t.oid),E'\n' order by t.tgname)) from pg_trigger t where not t.tgisinternal and t.tgrelid in ('public.orders'::regclass,'public.order_items'::regclass,'public.order_files'::regclass,'public.payments'::regclass)),
'grants',(select md5(string_agg(table_name||':'||grantee||':'||privilege_type,E'\n' order by table_name,grantee,privilege_type)) from information_schema.table_privileges where table_schema='public' and table_name in ('orders','order_items','order_files','payments','order_counters','quotes_read','payments_read','order_payment_summary') and grantee in ('anon','authenticated','service_role'))
) as fingerprint;
